#!/bin/bash
# Version 1.1-Alpha

docker stop seededdb
docker stop archangelui
docker stop archangelms

docker rmi -f $(docker images | grep 'mongo:seeded' | awk '{print $3}')
docker rmi -f $(docker images | grep 'archangelui' | awk '{print $3}')
docker rmi -f $(docker images | grep 'archangelms' | awk '{print $3}')

cwd=$(pwd)

mvn clean package

cd $cwd
cd frontend/docker
docker build --tag archangeui .

cd $cwd
cd service/docker
docker build --tag archangelms .

cd $cwd
cd database/docker
docker build --tag mongodb:seeded .

# start the database
docker run --name seededdb --rm -p 27017:27017 -ti -d mongodb:seeded

echo "starting ArchAngel Microservice"
# start the microservice
docker run --name archangelui --rm -p 8080:8080 -ti -d archangelui

echo "starting ArchAngel WebAppUI"
# start the Web-UI
docker run --name archangelms --rm -p 9000:8080 -ti -d archangelms

xhost=`hostname --ip-address`

echo ">>> The ArchAngel is now online"
echo "http://$xhost:8080"